apiVersion: v1
kind: Service
metadata:
  name: {{ include "json-store-web.fullname" . }}
  labels: {{- include "json-store-web.labels" . | nindent 4 }}
spec:
  selector: {{- include "json-store-web.selectorLabels" . | nindent 4 }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: http
